apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knative-apps
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/oavramenk/argocd-examples.git
    targetRevision: HEAD
    path: knative/
  destination: 
    server: https://kubernetes.default.svc
    namespace: knative-apps

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
