apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-python
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: docker.io/oavramenk/hello-world:0.1
        env:
        - name: TARGET
          value: "Python Sample v1"